<form class="form" action="" method="post">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Add new comment') ?></span></legend><br>
        <div class="field required">
            <label for="name" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Name') ?></span>
            </label>

            <div class="control">
                <input type="text" id="name"
                       name="number"
                       class="input-text" width="50%">
            </div>
        </div>
        <div class="field required">
            <label for="name" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Content') ?></span>
            </label>

            <div class="control">
                <textarea id="content"
                       name="content"
                       class="input-text">
                </textarea>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>