<H1><?php echo __('Lastest Blog Posts') ?></H1>
<ul class="blog-post-list">
	<?php foreach ($block->getComments() as $cmt): ?>
		<li class="blog-post-list-item">
			<h3 class="blog-post-item-title">
				<a href=""><?php echo $cmt->getAuthor() ?></a>
			</h3>

			<div class="blog-post-item-content">
				<?php echo $cmt->getContent() ?>
			</div>

			<div class="blog-post-item-meta">
				<strong><?php echo __('Created at: ') ?></strong> <?php echo $cmt->getCreationTime() ?>
			</div>

		</li>
	<?php endforeach; ?>
</ul>
