<script type="text/x-magento-init">
    {
        "*": {
            "OpenTechiz_Blog/js/commentajax": {
                "AjaxCommentPostUrl": "<?php echo $block->getFormAction() ?>",
                "AjaxCommentLoadUrl": "<?php echo $block->getAjaxUrl() ?>",
                "AjaxPostId": "<?php echo $block->getPostID(); ?>",
                "AjaxNotificationLoadUrl": "<?php echo $block->getAjaxNotificationLoadUrl(); ?>"
            }
        }
    }
</script>
<?php $helper = $this->helper('OpenTechiz\Blog\Helper\UserInfo'); ?>
<?php if($helper->isLoggedIn()) { ?>
<script id="blog-notification" type="text/x-magento-template">
    <li class="dropdown-item"><%- noti.content %></li>
</script>
<div class="customer-menu">
    <span class="counter qty action toggle"  data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
        <span class="title" id="noti-count"><?= __("Customer Menu"); ?></span>
    </span>
    <ul class="dropdown" id="notification-content">
    </ul>
</div>
<?php } ?>