
<script type="text/x-magento-init">
    {
        "[data-role=notifications]": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}
    }
</script>
<?php $helper = $this->helper('OpenTechiz\Blog\Helper\UserInfo'); ?>
<?php if($helper->isLoggedIn()) : ?>
<div class="authentication-wrapper" data-block="authentication" data-role="notifications" data-bind="scope: 'loadNotifications'" style="margin-top: 0px !important; width: : auto !important;">
    <button
        type="button"
        class="counter qty action action-auth-toggle"
        data-trigger="authentication">
        <span data-bind="text: loadNotifications().count, attr: { title:  loadNotifications().countCaption }"></span>
    </button>
    <div class="block-authentication"
         style="display: none"
         data-bind="mageInit: {
            'Magento_Ui/js/modal/modal':{
                'type': 'custom',
                'modalClass': 'authentication-dropdown',
                'trigger': '[data-trigger=authentication]',
                'wrapperClass': 'authentication-wrapper',
                'parentModalClass': '_has-modal-custom _has-auth-shown',
                'responsive': true,
                'responsiveClass': 'custom-slide',
                'overlayClass': 'dropdown-overlay modal-custom-overlay',
                'buttons': []
            }}">
        <div>
            <ul class="dropdown" id="notification-content" style="overflow-y: scroll; height:400px; padding: 5px;" data-bind="foreach: loadNotifications().items">
		    	<li class="dropdown-item">
			    	<!-- ko if: is_viewed == '0' -->
			    	<b data-bind="text: content"></b>
			    	<!-- /ko -->
		    		<!-- ko if: is_viewed == '1' -->
			    	<span data-bind="text: content"></span>
			    	<!-- /ko -->
			    	<br><small data-bind="text: creation_time"></small>
		    	</li>
		    </ul>
        </div>
    </div>
</div>
<?php endif; ?>