<p class="order_ship">
              <span class="paddingtop"><span class="icon">icon</span>Shipped within 24 hours</span>
              <abbr rel="tooltip" title="<p><span>Place your order today and this item will ship within 24 hours. </span></p>
<p><span>Shipping cost is $9.90 (flat rate) for any size order for standard Australia Post eParcel shipping with tracking. <br /><br />For Express Post options and delivery estimates please see&nbsp;</span>further details in cart.</p>"><i class="fa fa-question-circle fa-lg" aria-hidden="true"></i></abbr>
          </p>
<div class="product-right-bottom-wrapper">
              <div class="product-shipping-form">
                                  <div class="item"><em class="fa-fw fa fa-truck"></em><strong><span class="heading">Shipping cost is $9.90 (flat rate) for any size order.</span></strong></div>
<div class="item"><em class="fa-fw fa fa-thumbs-o-up"></em><span class="heading">This product is covered by an Australian Replacement Warranty.</span></div>
<div class="item"><em class="fa-fw fa fa-thumbs-o-up"></em><span class="heading">30 Days Money Back Guarantee. <a href="http://support.macfixit.com.au/article/48-30-day-money-back-guarantee" target="_blank">Click here</a> for more details.</span></div>                              </div>
            </div>